---
{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  #name: {{ include "parabol.rethinkdb-storage" . }}
  name: parabol-rethinkdb-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.rethinkdb.size }}
  {{- if .Values.persistence.rethinkdb.storageClass }}
  storageClassName: {{ .Values.persistence.rethinkdb.storageClass }}
  {{- end }}
{{- end }}
