
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "parabol.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "parabol.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "parabol.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "parabol.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "parabol.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh"]
        args: ["-c", "yarn db:migrate && yarn pg:migrate up && yarn postdeploy && yarn start"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: parabol
          protocol: TCP
          containerPort: 3000
        volumeMounts:
          - name: parabol-persistent-storage
            mountPath: /data
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: parabol-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "parabol.parabol-storage" }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
