---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    name: postgres-config
data:
  POSTGRES_DB: parabol-saas
  POSTGRES_USER: pgparaboladmin
  #POSTGRES_PASSWORD: test12345
  PGDATA: /var/lib/postgresql/data/pgdata
  postgresql.conf: |
    listen_addresses='*'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "parabol.postgres-storage" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "parabol.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "parabol.labels" . | nindent 4 }}
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      {{- include "parabol.labels" . | nindent 8 }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: postgres
        {{- include "parabol.labels" . | nindent 4 }}
    spec:
      containers:
      - name: postgres
        image: postgres:12.3
        envFrom:
          - configMapRef:
              name: postgres-config
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: cluster
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "parabol.postgres-storage" . }}
