---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "parabol.redis-storage" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "parabol.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "parabol.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "parabol.selectorLabels" . | nindent 6 }}
      app: redis
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "parabol.labels" . | nindent 8 }}
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2.8
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: cluster
        volumeMounts:
          - name: redis-persistent-storage
            mountPath: /data
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "parabol.redis-storage" . }}
