---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "parabol.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    {{- include "parabol.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: cluser
      port: 6379
  selector:
    {{- include "parabol.selectorLabels" . | nindent 4 }}
    app: redis
